deleteDependentEntities: true
createMissingRelatedEntities: true
repositoryType: 'all'
resources:
  - kind: aikido-issue-group
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '"aikido-issue-group-" + (.id|tostring)'
          title: .title
          blueprint: '"aikidoIssueGroup"'
          properties:
            type: .type
            description: .description
            severity_score: .severity_score
            severity: .severity
            group_status: .group_status
            time_to_fix_minutes: .time_to_fix_minutes
            locations: .locations
            how_to_fix: .how_to_fix
            related_cve_ids: .related_cve_ids

  - kind: aikido-issue
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '"aikido-issue-" + (.id|tostring)'
          title: '(.type + " - " + (.affected_package // "Unknown Package"))'
          blueprint: '"aikidoIssue"'
          properties:
            group_id: .group_id
            attack_surface: .attack_surface
            status: .status
            severity: .severity
            severity_score: .severity_score
            type: .type
            affected_package: .affected_package
            cve_id: .cve_id
            affected_file: .affected_file
            first_detected_at: .first_detected_at
            code_repo_id: .code_repo_id
            code_repo_name: .code_repo_name
            container_repo_id: .container_repo_id
            container_repo_name: .container_repo_name
            cloud_id: .cloud_id
            cloud_name: .cloud_name
            ignored_at: .ignored_at
            closed_at: .closed_at
            ignored_by: .ignored_by
            start_line: .start_line
            end_line: .end_line
            snooze_until: .snooze_until
            cwe_classes: .cwe_classes
            installed_version: .installed_version
            patched_versions: .patched_versions
            license_type: .license_type
            programming_language: .programming_language
            sla_days: .sla_days
            sla_remediate_by: .sla_remediate_by

  - kind: aikido-cloud-provider
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '"aikido-cloud-provider-" + (.id|tostring)'
          title: .name
          blueprint: '"aikidoCloudProvider"'
          properties:
            provider: .provider
            environment: .environment
            external_id: .external_id

  - kind: aikido-code-repository
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '"aikido-code-repository-" + (.id|tostring)'
          title: .name
          blueprint: '"aikidoCodeRepository"'
          properties:
            name: .name
            external_repo_id: .external_repo_id
            provider: .provider
            active: .active
            url: .url
            branch: .branch
            last_scanned_at: .last_scanned_at

  - kind: aikido-container-image
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '"aikido-container-image"'
          title: .name
          blueprint: '"aikidoContainerImage"'
          properties:
            name: .name
            provider: .provider
            registry_name: .registry_name
            tag: .tag
            last_scanned_at: .last_scanned_at
            last_scanned_tag: .last_scanned_tag

  - kind: aikido-issue-count
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '"aikido-issue-count"'
          title: '"Aikido Issue Counts"'
          blueprint: '"aikidoIssueCount"'
          properties:
            issue_groups: .issue_groups
            issues: .issues